language: go

go: 1.14.x

dist: xenial
arch: ppc64le

cache:
  directories:
  - vendor
  - $HOME/.cache/go-build
  - $HOME/gopath/bin
  - $HOME/gopath/pkg/mod


env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"


script:
- make build
